### PR TITLE
fixes #4 : files will highlighed when opened in Explorer

### LINKED ISSUE #4: [BUG] File should be highlighted in file explorer
**Describe the bug**
When you open a file or folder in the file explorer, its not highlighted, so its not obvious where it is.

**To Reproduce**
1. Open a folder or file
2. Right click on a file/folder in the file tree or open tab and click Open In Explorer
3. Once the file explorer shows up, it should open in the location the file is in, but it wont be highlighted in there

**Expected behavior**
After opening in the os file explorer, the file or folder should be highlighted so you don't have to go looking for it

### PR DESCRIPTION
**Pull request by ish-u**

### CODE REVIEW

File: src/components/Content/Editor/TabMenu.svelte [hunk 1]
```diff
@@ -47,9 +47,8 @@
     </ContextMenuOption>
     <ContextMenuOption labelText="Show in Explorer" on:click={() => {
         let dir = filepath.split(path.sep);
-        dir.pop();
-        dir = dir.join(path.sep);
-        shell.open(dir);
+        let explorerPath = dir.join(path.sep);
```
Comment (mellobacon) [inline src/components/Content/Editor/TabMenu.svelte:50]: There's no need to make a new variable here. Since `dir` is just `filepath` separated, joining it back together is repetitive. Might as well just use `filepath`.

**Review by mellobacon — CHANGES_REQUESTED** [review]

File: src/components/Content/Editor/TabMenu.svelte (hunk 1 above)
Comment (ish-u) [reply src/components/Content/Editor/TabMenu.svelte]: I have made the necessary changes
